import image01 from './assets/image01.jpg';
import image02 from './assets/image02.jpg';
import image03 from './assets/image03.jpg';
import image04 from './assets/image04.jpg';
import image05 from './assets/image05.jpg';
import image06 from './assets/image06.jpg';
import image07 from './assets/image07.jpg';
import image08 from './assets/image08.jpg';
import image09 from './assets/image09.jpg';
import image10 from './assets/image10.jpg';
import image11 from './assets/image11.jpg';
import image12 from './assets/image12.jpg';
import image13 from './assets/image13.jpg';
import image14 from './assets/image14.jpg';
import image15 from './assets/image15.jpg';
import image16 from './assets/image16.jpg';
import image17 from './assets/image17.jpg';
import image18 from './assets/image18.jpg';
import image19 from './assets/image19.jpg';
import image20 from './assets/image20.jpg';
import image21 from './assets/image21.jpg';
import image22 from './assets/mat.jpg';


const data = [
    { id: 1,
      romanNumber: "I",
      src: image01,
      title: 'I. El Mago (Le Bateleur)',
      title2: 'El Mago (Le Bateleur)',
      description: 'A pesar de las banalidades del día a día, esta carta te muestra que hay otras cosas más importantes. Es el primero de los Arcanos Mayores, por lo que presenta una fuerza especial. Tenés todo lo necesario para este momento.Los elementos que ves en la mesa simbolizan sus conocimientos y sabiduría. ¡Quien se atreve, gana!',
    },
    { id: 2,
      romanNumber: "II",
      src: image02,
      title: 'II. La Sacerdotisa (La Papesse)',
      title2: 'La Sacerdotisa (La Papesse)',
      description: 'Inmóvil y misteriosa. Es una carta que invita a la observación por sobre la acción. La introspección sobre la expansión.La sacerdotiza es una gran portadora de conocimiento. Si te sentís insatisfechx, tenes dos caminos: podes aumentar tu esfuerzo para lograr lo que quieras o reconciderar tus objetivos. Su energía es un puente entre el inconsciente y el consciente.',
    },
    { id: 3,
      romanNumber: "III",
      src: image03,
      title: "III. La Emperatriz (L'Impératrice)",
      title2: "La Emperatriz (L'Impératrice)",
      description: 'La Emperatriz ayuda a la comunicación entre nosotrxs y nuestrxs afectos. Esta carta fomenta la intimidad, por otro lado, también simboliza la fertilidad. El camino hacia lo Desconocido. ',
    },
    { id: 4,
      romanNumber: "IV",
      src: image04,
      title: "IV. El Emperador (L'Empereur)",
      title2: "El Emperador (L'Empereur)",
      description: 'Dominio de la mente por sobre el corazón. El Emperador representa poder y autoridad. Un momento de estabilidad, sobre todo en situaciones complejas. Te invita a que Disfrutes de lo material y Sacrifiques algunas tardes para construir algo. Esta carta nos habla de la autodisciplina, ¡Inspirate en el Emperador!',
    },
    { id: 5,
      romanNumber: "V",
      src: image05,
      title: 'V. El Papa (Le Pape)',
      title2: "El Papa (Le Pape)",
      description: 'El Papa simboliza la sabiduría y la madurez. Es una carta que escucha bien y brinda buenos consejos a todos. FE (no tiene que ser una fe religiosa). Esta carta trae una energía poderosamente espiritual. ',
    },
    { id: 6,
      romanNumber: "VI",
      src: image06,
      title: "VI. Los Enamorados (L'Amoureux)",
      title2: "Los Enamorados (L'Amoureux)",
      description: 'Los enamorados te muestr dos caminos, pasado y futuro. Viene de la mano con alguna decisión importante. también Es una carta que puede representar la inconstancia, especialmente porque no puede decidir por un camino. Su energía te invita a listar tus prioridades, volver a evaluar todo para elegir con que camino seguir adelante.',
    },
    { id: 7,
      romanNumber: "VII",
      src: image07,
      title: 'VII. El Carro (Le Chariot)',
      title2: "El Carro (Le Chariot)",
      description: 'El carro indica movimiento, el fin de las incertidumbres y la inestabilidad. Tiene una poderosa energía para sostener las riendas y fomenta actividades que te den nuevas experiencias (Viajar puede ser una de ellas). Esta carta puede ser un gran impulso si venis pensando en algo y no te animas.',
    },
    { id: 8,
      romanNumber: "VIII",
      src: image08,
      title: 'VIII. La Justicia (La Justice)',
      title2: "La Justicia (La Justice)",
      description: 'La justicia es una carta que promueve la MORALIDAD por sobre todo. Te quiere decir que lo que es, ES. Trae balance. Pone un énfasis en el cuidado de cada accion y cada palabra. La espada es un símbolo de respeto para ordenar o dar advertencia. La energía de La Justia te ayuda a tomar desiciones cuidadosamente y no en base a la intuición (como La Luna).',
    },
    { id: 9,
      romanNumber: "IX",
      src: image09,
      title: "IX. El Ermitaño (L'Ermite)",
      title2: "El Ermitaño (L'Ermite)",
      description: 'El Ermitaño simboliza simboliza la soledad y el retiro. Abre camino a la concentración en las relaciones. Se dedica a la meditación y la contemplación. Ilumina viejos pensamientos. Sumergite en tus recuerdos y pensa en lo que has manejado mejor y peor hasta ahora. Meditá. Es momento de enfrentarnos a nosotros mismxs para poder traer luz.',
    },
    { id: 10,
      romanNumber: "X",
      src: image10,
      title: 'X. La Rueda de la Fortuna (La Roue de Fortune)',
      title2: "La Rueda de la Fortuna (La Roue de Fortune)",
      description: 'Esta carta trae cambios drásticos. Oportunidades que se presentan. Tal como vemos en la carta, el futuro está subiendo. También, muestra cómo nuestro ciclo de vida es inestable. La felicidad es en este caso solo una cuestión de pura coincidencia. ¡Cuidado! La Suerte aleatoria suele ser muy inestable.',
    },
    { id: 11,
      romanNumber: "XI",
      src: image11,
      title: 'XI. La Fuerza (La Force)',
      title2: "La Fuerza (La Force)",
      description: 'Si tuviera que definir lo que es esta carta, elijo la palabra CORAJE. Esta carta tiene la habilidad de desenterrar sentimientos poderosos de amor, o consolidar relaciones existentes. Representa una mujer fuerte que puede hasta poner un animal salvaje de su lado. Pasión y poder INMENSO. ¡La motivación va a venir como consecuencia de un deseo interno muy grande!. La energía de La Fuerza te invita a sanar.',
    },
    { id: 12,
      romanNumber: "XII",
      src: image12,
      title: 'XII. El Colgado (Le Pendu)',
      title2: "El Colgado (Le Pendu)",
      description: 'Esta carta representa sumisión y obediencia, Puede tratarse de alguien que merezca un castigo y que tenga que hacerse cargo de las concecuencias de sus acciones. Por otor lado, El Colgado significa retrospección y un cambio en la percepción del tiempo y el espacio. Ahora comienza a mirar todo desde otra perspectiva.',
    },
    { id: 13,
      romanNumber: "XIII",
      src: image13,
      title: 'XIII. La Muerte (La Mort)',
      title2: "La Muerte (La Mort)",
      description: 'El arcano sin nombre porque en el Tarot, es imposible capturar este simbolismo con palabras. Cada iniciación de proceso interno, viene acompañado de una “muerte” simbólica, y como consecuencia, la resurrección de un nuevo YO. Dejá ir lo que tengas que dejar atrás, da lugar a algo nuevo.',
    },
    { id: 14,
      romanNumber: "XIV",
      src: image14,
      title: 'XIV. Templanza (Tempérance)',
      title2: "Templanza (Tempérance)",
      description: 'Esta carta representa armonía y reconciliación. Todo está estrechamente conectado, el mundo y nuestras acciones. Esta carta es una buena guía para pensar sobre el equilibrio de nuestras acciones. Su energía refleja una gran adaptación a tu entorno, hay una sinergia permanente fluyendo de manera natural.',
    },
    { id: 15,
      romanNumber: "XV",
      src: image15,
      title: 'XV. El Diablo (Le Diable)',
      title2: "El Diablo (Le Diable)",
      description: 'El diablo despierta los instintos e impulsos más salvajes y profundos. A pesar de su apariencia satánica, es una carta que promueve el buen trabajo gracias a la cantidad de energía que proporciona. ¡Cuidado! El Diablo puede indicar una verdadera anarquía que puede apoderarse fácilmente de tu vida.',
    },
    { id: 16,
      romanNumber: "XVI",
      src: image16,
      title: 'XVI. La Torre (La Maison Dieu)',
      title2: "La Torre (La Maison Dieu)",
      description: 'Cuando hablamos de La Torre, puede que pensemos que es una carta negativa. Esta carta propone un renacimiento despues del dolor y sufrimiento. No todo lo que se derrumba es una desgracia. Es símbolo de un perfecto de trabajo de construcción, pero está en ruinas por a la avaricia u orgullo de sus constructores. Prestá atención y aprovechala para purificar tu EGO.',
    },
    { id: 17,
      romanNumber: "XVII",
      src: image17,
      title: "XVII. La Estrella (L'Étoile)",
      title2: "La Estrella (L'Étoile)",
      description: 'La liberación del alma. La Estrella es protectora del futuro y símbolo de armonía. Reúne todos los ingredientes cruciales para que el cambio fluya lo más beneficioso posible. Trae esperanza, espiritualidad y su cualidad más hermosa: Renovación interna. ¿Quizás es momento? ¿Quizás ya lo venías pensando?',
    },
    { id: 18,
      romanNumber: "XVIII",
      src: image18,
      title: 'XVIII. La Luna (La Lune)',
      title2: "La Luna (La Lune)",
      description: 'La luna es el cuerpo astral mas brillante en nuestra oscura galaxia. Simboliza el calor del hogar, la nostalgia y las memorias (y puede que un poco, estemos atadxs al pasado). La luna no es una fuente de energía como el sol, solo recibe y refleja rayos que le llegan. Por eso es que principalmente es un simbolo de pasividad. Por otro lado, todo lo que vemos ahora en la superficie, tiene una profundidad mayor. Esta carta es un fuerte indicador de que permitas que tus ojos sean la intuición.',
    },
    { id: 19,
      romanNumber: "XIX",
      src: image19,
      title: 'XIX. El Sol (Le Soleil)',
      title2: "Sol (Le Soleil)",
      description: 'El Sol es LA INOCENCIA (como cuando eramos niñxs). Este es el pico de la individualidad, la etapa más alta de conjunción entre Espíritu y Alma. Esta gran experiencia interna solo puede compararse con el evento externo más impresionante que nosotrxs hayamos experimentado, el sol. Es una carta de muy buen pronóstico.',
    },
    { id: 20,
      romanNumber: "XX",
      src: image20,
      title: 'XX. El Juicio (Le Jugement)',
      title2: "El Juicio (Le Jugement)",
      description: 'Esta carta puede venir de la mano de un anuncio, un resultado favorable. Tiene un gran peso espiritual. Los Planes que venían tardando tiempo en llevarse a cabo, van a rendir sus frutos.',
    },
    { id: 21,
      romanNumber: "XXI",
      src: image21,
      title: 'XXI. El Mundo (Le Monde)',
      title2: "El Mundo (Le Monde)",
      description: 'El mundo. Una carta muy especial porque simboliza la perfección de la creación y el éxito. Trae consigo una señal de que la verdadera satisfacción está en camino y de que vas a ser recompensadx. El Mundo es la culminación de esfuerzos intensos y la llegada a la meta deseada. ¡El universo es perfecto y está de tu lado!',
    },
    { id: 22,
      romanNumber: "XXII",
      src: image22,
      title: 'El Loco (Le Mat)',
      title2: "El Loco (Le Mat)",
      description: 'El Loco pasa por la vida sin ninguna ambición u objetivo. Su energía representa abandonar la vida cómoda y embarcarse en un viaje hacia lo desconocido. Totalmente libres de deseos (prosperidad, riqueza, u otros). Los verdaderos valores son la experiencia INMEDIATA. Puede ayudarte a deshacerte de viejos patrones de vida o prejuicios. Tratá de mirar al mundo de manera imparcial como El Loco y descubrí detalles nuevos y desapercibidos.',
    },
  ];
  

  export default data;