import image01 from './assets/image01.jpg';
import image02 from './assets/image02.jpg';
import image03 from './assets/image03.jpg';
import image04 from './assets/image04.jpg';
import image05 from './assets/image05.jpg';
import image06 from './assets/image06.jpg';
import image07 from './assets/image07.jpg';
import image08 from './assets/image08.jpg';
import image09 from './assets/image09.jpg';
import image10 from './assets/image10.jpg';
import image11 from './assets/image11.jpg';
import image12 from './assets/image12.jpg';
import image13 from './assets/image13.jpg';
import image14 from './assets/image14.jpg';
import image15 from './assets/image15.jpg';
import image16 from './assets/image16.jpg';
import image17 from './assets/image17.jpg';
import image18 from './assets/image18.jpg';
import image19 from './assets/image19.jpg';
import image20 from './assets/image20.jpg';
import image21 from './assets/image21.jpg';
import image22 from './assets/mat.jpg';


const data = [
    { id: 1,
      romanNumber: "I",
      src: image01,
      title: 'I. El Mago (Le Bateleur)',
      title2: 'El Mago (Le Bateleur)',
      description: 'A pesar de las banalidades del día a día, el mago te muestra que hay otras cosas más importantes. Es el primer carta de los Arcanos Mayores, por lo que muestra una especial fuerza. ¡Quien se anima, gana! El mago te trae coraje, tenés todo lo necesario para este momento.',
    },
    { id: 2,
      romanNumber: "II",
      src: image02,
      title: 'II. La Sacerdotisa (La Papesse)',
      title2: 'La Sacerdotisa (La Papesse)',
      description: 'Inmóvil y misteriosa. Es una carta que invita a la observación sobre la acción, y la introspección sobre la expansión. Una gran portadora de conocimiento. Es una fuente de energía espiritual. Si te sentis insatisfechx, tenes dos caminos: Podes aumentar tu esfuerzo para lograr lo que quieras o reconciderar tus objetivos. Esta mujer simboliza el puente entre el inconsciente y el consciente. Si avanzamos hasta los límites de nuestra Consciencia, pasaremos a nuestro Inconsciente.',
    },
    { id: 3,
      romanNumber: "III",
      src: image03,
      title: "III. La Emperatriz (L'Impératrice)",
      title2: "La Emperatriz (L'Impératrice)",
      description: 'La Emperatriz  ayuda a la comunicación entre las personas, lo que fomenta la intimidad y el cuidado como resultado. Es el símbolo de la fertilidad. El camino hacia lo Desconocido.',
    },
    { id: 4,
      romanNumber: "IV",
      src: image04,
      title: "IV. El Emperador (L'Empereur)",
      title2: "El Emperador (L'Empereur)",
      description: 'Armonía y consideración hacia otras personas. Demuestra un momento de estabilidad, sobre todo en situaciones complejas. Autoridad. También te dice que No te quedes solo con la idea. Sacrificá un poco de tu tiempo y construí algo. Compromiso.',
    },
    { id: 5,
      romanNumber: "V",
      src: image05,
      title: 'V. El Papa (Le Pape)',
      title2: "El Papa (Le Pape)",
      description: 'El Papa simboliza la sabiduría y la madurez. Es una carta que escucha bien y brinda buenos consejos a todos. Fe, no tiene que ser una fe religiosa, FE. Vida espiritual. La fe mueve montañas.',
    },
    { id: 6,
      romanNumber: "VI",
      src: image06,
      title: "VI. Los Enamorados (L'Amoureux)",
      title2: "Los Enamorados (L'Amoureux)",
      description: 'Los enamorados simbolizan dos caminos, uno pasado y otro futuro. Toma de desiciones importantes. Progreso. Es una carta que puede representar la inconstancia, especialmente porque no puede decidir por un camino.',
    },
    { id: 7,
      romanNumber: "VII",
      src: image07,
      title: 'VII. El Carro (Le Chariot)',
      title2: "El Carro (Le Chariot)",
      description: 'El carro indica que las incertidumbres y la inestabilidad llegarán a su fin. Movimiento. Tiene una poderosa energía para sostener las riendas y fomenta actividades que brindan una nueva experiencia. Viajar es el más natural de ellos. Esta carta puede ser un gran impulso si venis pensando en viajar y no te animas.',
    },
    { id: 8,
      romanNumber: "VIII",
      src: image08,
      title: 'VIII. La Justicia (La Justice)',
      title2: "La Justicia (La Justice)",
      description: 'La justicia promueve moralidad por sobre todo. Te quiere decir que lo que es, ES. Es la guardiana de la estabilidad. Pone un enfasis en el cuidado de cada accion y cada palabra. La justicia siempre va a hacer desiciones cuidadosamente y no en base a la intuición, instinto o el estado animico del momento. Sabiduría. Equilibrio de las fuerzas buenas y malas, como el ying y el yang.',
    },
    { id: 9,
      romanNumber: "IX",
      src: image09,
      title: "IX. El Ermitaño (L'Ermite)",
      title2: "El Ermitaño (L'Ermite)",
      description: 'El Ermitaño simboliza simboliza la soledad y el retiro. Abre camino a la concentración en las relaciones. El ermitaño es un hombre sabio que vive en reclusión. Se dedica a la meditación y la contemplación. Ilumina viejos pensamientos. Sumergite en tus recuerdos y pensa en lo que has manejado mejor y peor hasta ahora. Meditá. Es momento de enfrentarnos a nosotros mismxs para poder traer luz.',
    },
    { id: 10,
      romanNumber: "X",
      src: image10,
      title: 'X. La Rueda de la Fortuna (La Roue de Fortune)',
      title2: "La Rueda de la Fortuna (La Roue de Fortune)",
      description: 'La Rueda de la fortuna trae Cambios drásticos. Oportunidades que se presentan. La felicidad es en este caso solo una cuestión de pura coincidencia. ¡Ojo! la Suerte aleatoria suele ser muy inestable.',
    },
    { id: 11,
      romanNumber: "XI",
      src: image11,
      title: 'XI. La Fuerza (La Force)',
      title2: "La Fuerza (La Force)",
      description: 'La Fuerza tiene la habilidad de desenterrar sentimientos poderosos de amor o consolidar relaciones existentes. Te permite seguir a pesar de la fatiga. Representa una mujer fuerte que puede hasta poner un animal salvaje de su lado. La motivación vendrá como consecuencia de un deseo interno muy grande! La fuerza, también propone sanar.',
    },
    { id: 12,
      romanNumber: "XII",
      src: image12,
      title: 'XII. El Colgado (Le Pendu)',
      title2: "El Colgado (Le Pendu)",
      description: 'El Colgado significa retrospección, un cambio en la percepción del tiempo y el espacio. Ahora vas a comenzar a mirar todo desde otra perspectiva.',
    },
    { id: 13,
      romanNumber: "XIII",
      src: image13,
      title: 'XIII. La Muerte (La Mort)',
      title2: "La Muerte (La Mort)",
      description: 'Cada iniciación de proceso interno, viene acompañado de una “muerte” simbólica. La resurrección de un nuevo YO. Es el arcano sin nombre porque en Tarot, el simbolismo no puede ser capturado en palabras. Dejar lo que tengamos que dejar atrás da lugar a algo nuevo.',
    },
    { id: 14,
      romanNumber: "XIV",
      src: image14,
      title: 'XIV. Templanza (Tempérance)',
      title2: "Templanza (Tempérance)",
      description: 'Esta carta simboliza la armonía y reconciliación. El mundo y nuestras acciones están estrechamente conectadas. Esta carta es una buena guía para pensar sobre el equilibrio de nuestras acciones.',
    },
    { id: 15,
      romanNumber: "XV",
      src: image15,
      title: 'XV. El Diablo (Le Diable)',
      title2: "El Diablo (Le Diable)",
      description: 'El diablo despierta los instintos más fuertes y los impulsos más profundos. A pesar de su apariencia, puede ser una tarjeta que promueve el buen trabajo gracias a la cantidad de energía que se pone. El Diablo indica verdadera anarquía, ¡Ojo! esa anarquía puede apoderarse fácilmente de tu vida.',
    },
    { id: 16,
      romanNumber: "XVI",
      src: image16,
      title: 'XVI. La Torre (La Maison Dieu)',
      title2: "La Torre (La Maison Dieu)",
      description: 'La torre no representa solo negatividad, propone un renacimiento despues del dolor y sufrimiento. No todo lo que se derrumba es malo. La torre purifica el Ego.',
    },
    { id: 17,
      romanNumber: "XVII",
      src: image17,
      title: "XVII. La Estrella (L'Étoile)",
      title2: "La Estrella (L'Étoile)",
      description: 'La liberación del alma. La estrella es protectora del futuro y símbolo de armonía, reúne todos los ingredientes cruciales para que el cambio sea lo más fácil y beneficioso posible. Presenta un período de descanso para vos. Esta renovación puede ser spiritual, física o ambas.',
    },
    { id: 18,
      romanNumber: "XVIII",
      src: image18,
      title: 'XVIII. La Luna (La Lune)',
      title2: "La Luna (La Lune)",
      description: 'La luna es el cuerpo astral mas brillante. Simboliza el calor del hogar, la nostalgia, las memorias y estar atadxs al pasado. La luna no es una fuente de energia como el sol, solo recibe y refleja rayos que le llegan. Por eso es que es principalmente un simbolo de pasividad.',
    },
    { id: 19,
      romanNumber: "XIX",
      src: image19,
      title: 'XIX. El Sol (Le Soleil)',
      title2: "Sol (Le Soleil)",
      description: 'El sol representa la inocencia como cuando eramos niñxs. Este es el pico de la individualidad, la etapa más alta de conjunción entre Espíritu y Alma. Esta gran experiencia interna solo puede compararse con el evento externo más impresionante que el ser vivo haya experimentado, el sol.',
    },
    { id: 20,
      romanNumber: "XX",
      src: image20,
      title: 'XX. El Juicio (Le Jugement)',
      title2: "El Juicio (Le Jugement)",
      description: 'El Juicio puede anunciar un cambio, un resultado favorable de un proyecto a largo plazo. Tiene un gran peso espiritual. Planes que venian tardando tiempo en llevarse a cabo, van a rendir frutos.',
    },
    { id: 21,
      romanNumber: "XXI",
      src: image21,
      title: 'XXI. El Mundo (Le Monde)',
      title2: "El Mundo (Le Monde)",
      description: 'Una carta muy especial porque Simboliza la perfección de la creación y el éxito. Es una señal de que la verdadera satisfacción está en camino y de que vas a ser recompensadx por tu duro trabajo. La llegada de la meta deseada. El universo es perfecto.',
    },
    { id: 22,
      romanNumber: "XXII",
      src: image22,
      title: 'El Loco (Le Mat)',
      title2: "El Loco (Le Mat)",
      description: 'El loco representa pasar por la vida sin ninguna ambición u objetivo. Simboliza abandonar la vida cómoda y se embarcar en un viaje hacia lo desconocido. Totalmente libres de deseos de riqueza. Los verdaderos valores son la experiencia inmediata. Puede ayudarte a deshacerte de viejos patrones de vida o prejuicios. Trate de mirar al mundo de manera imparcial como el tonto y descubrir detalles nuevos y desapercibidos.',
    },
  ];
  

  export default data;