import image01 from './assets/image01.png';
import image02 from './assets/image02.png';
import image03 from './assets/image03.png';
import image04 from './assets/image04.png';
import image05 from './assets/image05.png';
import image06 from './assets/image06.png';
import image07 from './assets/image07.png';
import image08 from './assets/image08.png';
import image09 from './assets/image09.png';
import image10 from './assets/image10.png';
import image11 from './assets/image11.png';
import image12 from './assets/image12.png';
import image13 from './assets/image13.png';
import image14 from './assets/image14.png';
import image15 from './assets/image15.png';
import image16 from './assets/image16.png';
import image17 from './assets/image17.png';
import image18 from './assets/image18.png';
import image19 from './assets/image19.png';
import image20 from './assets/image20.png';
import image21 from './assets/image21.png';
import image22 from './assets/mat.png';

const data = [
    { id: 1,
      romanNumber: "I",
      src: image01,
      title: "cards.magician",
      title2:"cards.magician",
      description: "cards.magician-content",
    },
    { id: 2,
      romanNumber: "II",
      src: image02,
      title: "cards.popess",
      title2: "cards.popess",
      description: "cards.popess-content",
    },
    { id: 3,
      romanNumber: "III",
      src: image03,
      title: "cards.empress",
      title2:"cards.empress",
      description: "cards.empress-content",
    },
    { id: 4,
      romanNumber: "IV",
      src: image04,
      title: "cards.emperor",
      title2: "cards.emperor",
      description: "cards.emperor-content",
    },
    { id: 5,
      romanNumber: "V",
      src: image05,
      title: 'cards.pope',
      title2: 'cards.pope',
      description: 'cards.pope-content',
    },
    { id: 6,
      romanNumber: "VI",
      src: image06,
      title: "cards.lover",
      title2: "cards.lover",
      description: 'cards.lover-content',
    },
    { id: 7,
      romanNumber: "VII",
      src: image07,
      title: 'cards.chariot',
      title2: 'cards.chariot',
      description: 'cards.chariot-content',
    },
    { id: 8,
      romanNumber: "VIII",
      src: image08,
      title: 'cards.justice',
      title2: 'cards.justice',
      description: 'cards.justice-content',
    },
    { id: 9,
      romanNumber: "IX",
      src: image09,
      title: "cards.hermit",
      title2: "cards.hermit",
      description: 'cards.hermit-content',
    },
    { id: 10,
      romanNumber: "X",
      src: image10,
      title: 'cards.wheel',
      title2: 'cards.wheel',
      description: 'cards.wheel-content',
    },
    { id: 11,
      romanNumber: "XI",
      src: image11,
      title: 'cards.strength',
      title2: 'cards.strength',
      description: 'cards.strength-content',
    },
    { id: 12,
      romanNumber: "XII",
      src: image12,
      title: 'cards.hanged',
      title2: 'cards.hanged',
      description: 'cards.hanged-content',
    },
    { id: 13,
      romanNumber: "XIII",
      src: image13,
      title: 'cards.death',
      title2: 'cards.death',
      description: 'cards.death-content',
    },
    { id: 14,
      romanNumber: "XIV",
      src: image14,
      title: 'cards.temperance',
      title2: 'cards.temperance',
      description: 'cards.temperance-content',
    },
    { id: 15,
      romanNumber: "XV",
      src: image15,
      title: 'cards.devil',
      title2: 'cards.devil',
      description: 'cards.devil-content',
    },
    { id: 16,
      romanNumber: "XVI",
      src: image16,
      title: 'cards.tower',
      title2: 'cards.tower',
      description: 'cards.tower-content',
    },
    { id: 17,
      romanNumber: "XVII",
      src: image17,
      title: "cards.star",
      title2: "cards.star",
      description: 'cards.star-content',
    },
    { id: 18,
      romanNumber: "XVIII",
      src: image18,
      title: 'cards.moon',
      title2: 'cards.moon',
      description: 'cards.moon-content',
    },
    { id: 19,
      romanNumber: "XIX",
      src: image19,
      title: 'cards.sun',
      title2: 'cards.sun',
      description: 'cards.sun-content',
    },
    { id: 20,
      romanNumber: "XX",
      src: image20,
      title: 'cards.judgement',
      title2: 'cards.judgement',
      description: 'cards.judgement-content',
    },
    { id: 21,
      romanNumber: "XXI",
      src: image21,
      title: 'cards.world',
      title2: 'cards.world',
      description: 'cards.world-content',
    },
    { id: 22,
      romanNumber: "XXII",
      src: image22,
      title: 'cards.fool',
      title2: 'cards.fool',
      description: 'cards.fool-content',
    },
  ];
  

  export default data;
  // export default withTranslation('data')(data)